name: smart_dispenser
description: wallet for blockchain based smart dispenser created by Amrita WNA.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eva_icons_flutter: ^2.0.0
  share: ^0.6.2+1
  qr_flutter: ^3.2.0
  flutter_qr_scanner: ^0.1.5

dev_dependencies:

  flutter_launcher_icons: ^0.7.2+1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/icon.png

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/infographics/undraw_done_checking_ty9a.svg

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf